export const TodoActions = {
    ADD: 'TODO_ADD',
    DELETE: 'TODO_DELETE',
    RENAME: 'TODO_RENAME',
    PRIORITY: 'TODO_PRIORITY',
    COMPLETED: 'TODO_COMPLETED',
    TOGGLE_TRACKING: 'TODO_TOGGLE_TRACKING',
    SYNC_TIME: 'TODO_SYNC_TIME' 
};
